---
title: "Trabajo 1. Teoría de la Decisión. Enunciados y soluciones"
author: "Grupo 3. Lucía García Infante, Rosa Fernandez López, Sergio Pacheco Márquez, Víctor Silva Nieves"
format: 
  html:
    toc: true
    toc-depth: 3
    toc-expand: true
    toc-location: left
    code-fold: false
    theme:
      - cosmo
      - estilo/tema.scss
  typst: 
    toc: true
    toc-depth: 3
    include-before-body: estilo/toc-sep.typ
    code-fold: false
    brand: _brand.yml"
lang: es
---

# EJERCICIO 1. Lucía García Infante

## Problema 1.1
Aplicar los criterios de decisión bajo incertidumbre al siguiente problema considerando una situación favorable (beneficios) y desfavorable (costos)

|    | e1  | e2  | e3  | e4  | e5  | e6  |
|----|-----|-----|-----|-----|-----|-----|
| d1 | 100 | 200 | 130 | 150 | 240 | 100 |
| d2 | 300 | 145 | 230 | 345 | 200 | 280 |
| d3 | 120 | 300 | 260 | 400 | 100 | 330 |
| d4 | 180 | 130 | 300 | 370 | 280 | 190 |
| d5 | 200 | 140 | 135 | 280 | 190 | 100 |



## Problema 1.2

Marina es una alumna del grado en Estadística que acaba este año. El próximo año quiere realizar un máster para mejorar sus oportunidades laborales, pero solo puede escoger uno.
Todavía no sabe en qué sitio empezará a trabajar aunque considera tres posibilidades:

- Una **empresa privada en el extranjero**.
- Una **institución pública**.
- Una **empresa privada española**.

Para decidir, Marina ha mirado tres másteres que le interesan y ha estimado cuál podría ser su primer sueldo anual según el tipo de empresa, junto con el coste de cada máster:

- **Máster en Análisis de Datos**. Espera ganar unos 26.000 € en una empresa extranjera, 18.000 € en una institución pública y 20.000 € en una empresa española. Este máster tiene un coste de 10.000 €.
- **Máster en Programación y Modelos Estadístico**. Estima que su sueldo inicial sería de 20.000 € en una empresa extranjera, 12.000 € en una institución pública y 20.000 € en una empresa privada española. El coste de este máster asciende a 6.500 €.
- **Máster en Comunicación y Gestión de Proyectos**. Espera un sueldo de 10.000 € en una empresa extranjera, 12.000 € en una institución pública y 20.000 € en una empresa privada española. Este máster tiene un coste de 3.000 €.



# EJERCICIO 2. Rosa Fernández López

## Problema 2.1

Aplicar los criterios de decisión bajo incertidumbre (tanto en situación favorable
como desfavorable) a los problemas cuya matriz de valores numéricos viene dada en la tabla siguiente:

|  | e1 | e2 | e3 |
|:------|:----:|:----:|:----:|
| **d1**| 12 | 8  | 5  |
| **d2**| 10 | 11 | 4  |
| **d3**| 7  | 13 | 6  |


## Problema 2.2

**Elección de tarifa eléctrica para un nuevo piso**

Carlos se ha mudado recientemente a un nuevo piso y necesita contratar una tarifa de electricidad. Tras comparar varias compañías, ha identificado tres opciones con condiciones distintas:

- ElectroPlus ofrece una tarifa fija de 45€ al mes, independientemente del consumo eléctrico.

- LuzFlex aplica una tarifa variable de 0,20€/kWh, con una cuota base mensual de 15€.

- EcoVolt propone una tarifa variable de 0,15€/kWh sin cuota fija, pero incluye una penalización de 10€ si el consumo mensual supera los 300kWh.

Carlos no tiene certeza sobre su consumo mensual, pero considera dos escenarios posibles durante el primer año:

- Consumo moderado: 250kWh al mes.

- Consumo elevado: 350kWh al mes.

Determinar cuál sería la mejor opción para Carlos según cada criterio.

# EJERCICIO 3. Sergio Pacheco Márquez

## Problema 3.1

Una empresa de tecnología debe escoger la estrategia de lanzamiento de un nuevo dispositivo.\
Las alternativas son:

-   **E1:** Lanzamiento enfocado en publicidad en redes sociales.\
-   **E2:** Lanzamiento con campaña televisiva nacional.\
-   **E3:** Lanzamiento mixto (online + medios tradicionales).

El resultado económico (beneficio en miles de euros) depende del estado del mercado:\
**S1** (Alta demanda), **S2** (Demanda media) y **S3** (Baja demanda).

Se dispone de la siguiente tabla de pagos (beneficios en miles de euros):

| **Estrategia** | **S1 (Alta demanda)** | **S2 (Demanda media)** | **S3 (Baja demanda)** |
|:----------------|-----------------:|------------------:|-----------------:|
| **E1** | 80 | 40 | 10 |
| **E2** | 100 | 50 | -20 |
| **E3** | 70 | 60 | 30 |

## Problema 3.2

Una empresa de energías renovables debe decidir la localización de una nueva planta solar fotovoltaica.\
Las alternativas de localización son:

-   **L1:** Andalucía\
-   **L2:** Castilla-La Mancha\
-   **L3:** Aragón

El beneficio proyectado (en millones de euros) depende del nivel de radiación solar anual, que se puede clasificar en tres escenarios posibles:\
**S1** (Alta), **S2** (Media) y **S3** (Baja).

Los beneficios estimados son los siguientes:

| **Localización**            | **S1 (Alta)** | **S2 (Media)** | **S3 (Baja)** |
|:----------------------------|--------------:|---------------:|--------------:|
| **L1 (Andalucía)**          |            12 |              8 |             3 |
| **L2 (Castilla-La Mancha)** |            10 |              9 |             6 |
| **L3 (Aragón)**             |            11 |              7 |             4 |

# EJERCICIO 4. Víctor Silva Nieves

## Problema 4.1

Se deben implementar todos los métodos de decisión bajo incertidumbre, tanto para el caso favorable como para el caso desfavorable (pesimista, optimista, Hurwicz, Savage, Laplace y punto ideal) para la siguiente tabla de decisión:

|       | $\omega_1$ | $\omega_2$ | $\omega_3$ | $\omega_4$ |
|-------|------------|------------|------------|------------|
| $a_1$ | 5          | 15         | 8          | 18         |
| $a_2$ | 7          | 13         | 14         | 20         |
| $a_3$ | 6          | 17         | 11         | 17         |
| $a_4$ | 4          | 14         | 16         | 16         |
| $a_5$ | 10         | 10         | 13         | 15         |

## Problema 4.2

Una persona recibe una herencia de 200.000 euros y se le presentan diferentes opciones de inversión para los próximos 10 años.

Puede terminar de pagar su hipoteca actual, ahorrando 40.000 euros de intereses y le sobrarían 30.000 euros que pondría en una cuenta remunerada al 2% anual

Puede seguir pagando su hipoteca y elegir una de las siguientes opciones

* Adquirir un piso por esa cantidad y si los alquileres turísticos siguen siendo posibles podrá generar un 6% anual. Si por el contrario se regularan pasaría a perder un 1% anual.
* Invertir en un fondo indexado que le puede generar un 7% anual pero si la bolsa baja perderá un 8%.
* Invertir en una franquicia de una cadena de comida rápida. Si acierta con el sitio podrá generar un 10% anual pero si se equivoca al seleccionar el sitio incurrirá en unas pérdidas anuales del 10%
